# Generated by Django 3.1 on 2020-08-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photolog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photolog',
        ),
    ]
